//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatDiplom.Models.PlatModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class About_banks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public About_banks()
        {
            this.PaymentsRU = new HashSet<PaymentsRU>();
        }
    
        public int Bank_ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Bank { get; set; }
        public string Account { get; set; }
        public string Ref { get; set; }
        public string RegCode { get; set; }
        public string AccountN { get; set; }
        public string NameUkr { get; set; }
        public string NameEngRus { get; set; }
        public string BankCorrespondent { get; set; }
        public string CorrespondentField { get; set; }
        public string BankIndex { get; set; }
        public Nullable<int> BankLevel { get; set; }
        public string Index_IN { get; set; }
        public string Index_OUT { get; set; }
        public string SpecialCodeName { get; set; }
        public string SpecialCodes { get; set; }
        public string DetailsOfPayment { get; set; }
        public string BeneficiaryAddress { get; set; }
        public string Registration { get; set; }
        public string NameFirmOtherLang { get; set; }
        public string AddressFirmOtherLang { get; set; }
        public string NameFirmEng { get; set; }
        public string AddressFirmEng { get; set; }
        public string DirectorOtherLang { get; set; }
        public string DirectorEng { get; set; }
        public string Patentname { get; set; }
        public string PatentNameEng { get; set; }
        public string Beneficiary_bank { get; set; }
        public string Intermediary_bank { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentsRU> PaymentsRU { get; set; }
    }
}
