//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatDiplom.Models.PlatModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLogWebIpAddress
    {
        public int AccessLogWebIpAddressID { get; set; }
        public string IpAddress { get; set; }
        public bool IsAllowed { get; set; }
        public string IpAddressDescription { get; set; }
    }
}
