//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatDiplom.Models.PlatModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebitNotes
    {
        public int ID_DN { get; set; }
        public string No { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Case { get; set; }
        public string To { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<decimal> Sum1 { get; set; }
        public Nullable<decimal> Sumплатить { get; set; }
        public Nullable<decimal> Official { get; set; }
        public string Appl_ID { get; set; }
        public string F_ID { get; set; }
        public Nullable<bool> Access_level { get; set; }
        public string File { get; set; }
        public string TempDoc { get; set; }
        public string FinalPDF { get; set; }
        public Nullable<System.DateTime> PDFValidTill { get; set; }
        public string Ref { get; set; }
        public Nullable<decimal> Sum_ { get; set; }
        public Nullable<decimal> SumEURO { get; set; }
        public Nullable<decimal> SumUA { get; set; }
        public Nullable<decimal> SumRU { get; set; }
        public string Akt { get; set; }
        public string UserID { get; set; }
        public Nullable<decimal> Result { get; set; }
        public Nullable<decimal> Sum1_EURO_inf { get; set; }
        public Nullable<decimal> Credit_note { get; set; }
        public Nullable<decimal> Official_EURO { get; set; }
        public Nullable<int> x { get; set; }
        public string Action { get; set; }
        public string FilePaid { get; set; }
        public string Index { get; set; }
        public string Changes { get; set; }
        public Nullable<int> BankIndex { get; set; }
        public Nullable<decimal> dnSum { get; set; }
        public Nullable<int> dnCurrency_id { get; set; }
        public Nullable<decimal> dnSumOfficial { get; set; }
        public Nullable<int> dnOfficialCurrency_id { get; set; }
        public string TMP_field { get; set; }
        public Nullable<int> pdn_index { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<decimal> CreditTax { get; set; }
        public Nullable<int> AgreementId { get; set; }
        public Nullable<System.DateTime> ActDate { get; set; }
        public Nullable<int> ActionsBy { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
