//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatDiplom.Models.PlatModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrePayment
    {
        public int id_prepayment { get; set; }
        public string PreTaxNum { get; set; }
        public string PreTaxName { get; set; }
        public Nullable<decimal> PreSum { get; set; }
        public Nullable<System.DateTime> DatePre { get; set; }
        public Nullable<decimal> remainder { get; set; }
        public Nullable<bool> Done { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> currency_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public bool Active { get; set; }
    }
}
