//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatDiplom.Models.PlatModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTariffsUA
    {
        public int ActionID { get; set; }
        public Nullable<int> Numeration { get; set; }
        public Nullable<int> PaymentCodeAll { get; set; }
        public Nullable<int> Payment_Code { get; set; }
        public string ActionName { get; set; }
        public string ActionName_in_UKRLong { get; set; }
        public string ActionName_in_UKR { get; set; }
        public string ActionNameForDN { get; set; }
        public Nullable<decimal> Official_fee_less { get; set; }
        public Nullable<decimal> Official_fee_fullNew { get; set; }
        public string ActionName_OfficialForInvoice { get; set; }
        public string Percentage { get; set; }
        public Nullable<short> Criteria { get; set; }
        public Nullable<decimal> Tariff { get; set; }
        public string Country { get; set; }
        public string Примечание { get; set; }
        public string Currency { get; set; }
        public Nullable<short> FormatField1NAF { get; set; }
        public Nullable<bool> AdditionalField { get; set; }
        public string ApplicationStage { get; set; }
        public string P_T_D { get; set; }
        public Nullable<decimal> TariffUA { get; set; }
        public string ApplicationStage_UA { get; set; }
        public Nullable<short> FormatField_UA { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<int> TypeCase { get; set; }
        public Nullable<int> Currency_id { get; set; }
        public Nullable<decimal> Official_fee_full { get; set; }
    
        public virtual PTariffsUA PTariffsUA1 { get; set; }
        public virtual PTariffsUA PTariffsUA2 { get; set; }
    }
}
