//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatDiplom.Models.PlatModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurofPayment
    {
        public int id_PurofPayment { get; set; }
        public string PurofPayment1 { get; set; }
        public Nullable<int> lenght { get; set; }
        public Nullable<int> Department_id { get; set; }
        public Nullable<int> Country_id { get; set; }
    }
}
