//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatDiplom.Models.PlatModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserGroups()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int id_group { get; set; }
        public string Groupname { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserRightsOverrideID { get; set; }
        public Nullable<bool> EditTrDueDates { get; set; }
        public Nullable<bool> EditTrDeadlines { get; set; }
        public Nullable<bool> EditTrFilingDate { get; set; }
        public Nullable<bool> EditShedules { get; set; }
        public Nullable<bool> ViewClientPages { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public Nullable<bool> EditPrDueDate { get; set; }
        public Nullable<bool> EditPrDeadlines { get; set; }
        public Nullable<bool> EditPrFilingDate { get; set; }
        public Nullable<bool> EditUserRights { get; set; }
        public Nullable<bool> CreateDebitNotes { get; set; }
        public Nullable<bool> ViewDebitNotes { get; set; }
        public Nullable<bool> EditDebitNotes { get; set; }
        public Nullable<bool> DebitNotesLevel2 { get; set; }
        public Nullable<bool> ViewUnpaidDNsOnly { get; set; }
        public Nullable<bool> Accounting { get; set; }
        public Nullable<bool> CanGiveMoneyToCash { get; set; }
        public Nullable<bool> IsSecretary { get; set; }
        public Nullable<bool> Agents_SF { get; set; }
        public Nullable<bool> RestrictedAccess { get; set; }
        public Nullable<bool> EditCases { get; set; }
        public Nullable<bool> ViewPersons { get; set; }
        public Nullable<bool> EditPersons { get; set; }
        public bool AllowRemoteAccess { get; set; }
        public bool AllowRemoteAccessExclusively { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
